version: "3.9"
   
services:
  
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
    restart: always
    container_name: db_logia_container
    
  api:
    build: .
    command: python3 manage.py runserver 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    container_name: api_logia_container
    
    depends_on:
      - db